name: tb_alkhalij
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  validate: ^1.7.0
  video_player: ^0.10.1+2
  shared_preferences: ^0.5.2+1
  json_annotation: ^2.0.0
  google_fonts_arabic: ^1.1.7
  google_maps_flutter: ^0.5.5
  location: ^2.3.5
  font_awesome_flutter: ^8.0.0
  flutter_calendar: ^0.0.8
  flutter_calendar_carousel: ^1.3.10
  flutter_datetime_picker:


  dio: ^2.1.13
  scoped_model: ^1.0.1
  smooth_star_rating: 1.0.2
  rflutter_alert: ^1.0.2
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  url_launcher: ^5.0.2
  http: ^0.12.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png
   - assets/background_video.mp4
   - assets/person.png
   - assets/bg.png
   - assets/photo_camera.png
   - assets/avatar.png
   - assets/avatar_person.png

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Amiri-Italic.ttf
        - asset: assets/fonts/Amiri-Regular.ttf